### ISSUE TITLE
Cursor jumps to the end after deleting one symbol

### ISSUE THREAD

**Issue by DKKovalev** [vacxe/PhoneMask#12]

**Comment by DKKovalev** [comment]
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/5726643/26498743/bec82c02-4238-11e7-87d1-d20e357546f1.gif)

**Comment by Vacxe** [comment]
@DKKovalev can u download latest version of master branch and test new functional? Its work for u?

**Comment by DKKovalev** [comment]
Yes, everything works fine, thank you

**Comment by Vacxe** [comment]
@DKKovalev i will compile 1.0.3 ver today
